demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo_app.urls')),
]

demo_app/urls.py
from django.urls import path, re_path

from . import views

app_name = 'demo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^(?P<q_date>\d{4}-\d{2}-\d{2})$', views.DateView.as_view(), name='date'),
    re_path(r'^(?P<q_date>\d{4}-\d{2}-\d{2})/(?P<q_publisher>\d+)$', views.PublisherView.as_view(), name='publisher'),
]

demo_app/models.py
from django.db import models
from django.urls import reverse

class Publisher(models.Model):
    name = models.CharField(max_length=50)

class Source(models.Model):
    name = models.CharField(max_length=100)

class RevenueRecord(models.Model):
    date = models.DateField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    clicks = models.IntegerField()
    revenue = models.FloatField()

demo_app/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.views import View
from django_tables2 import SingleTableView, RequestConfig
from .models import RevenueRecord, Publisher, Source
from .tables import RevenueTable, DateTable, PublisherTable
from django.shortcuts import render, get_object_or_404
import datetime

class IndexView(View):
    def get(self, request):
        table = RevenueTable(RevenueRecord.objects.values('date').annotate(revenue_sum=Sum('revenue'), clicks_sum=Sum('clicks')).order_by('-date'))

        RequestConfig(request).configure(table)
        table.paginate(page=request.GET.get("page", 1), per_page=15)
        return render(request, 'index_template.html', {'table': table})

class DateView(View):
    def get(self, request, q_date):
        ddate = datetime.datetime.strptime(q_date,"%Y-%m-%d").strftime("%B %d, %Y")
        table = DateTable(RevenueRecord.objects.filter(date=q_date).values('date', 'publisher','publisher__name').annotate(revenue_sum=Sum('revenue'), clicks_sum=Sum('clicks')).order_by('publisher__name'))

        RequestConfig(request).configure(table)
        return render(request, 'date_template.html', {'table': table, 'q_date': ddate})

class PublisherView(SingleTableView):
    def get(self, request, q_date, q_publisher):
        publisher = get_object_or_404(Publisher, id=q_publisher)
        ddate = datetime.datetime.strptime(q_date,"%Y-%m-%d").strftime("%B %d, %Y")
        table = PublisherTable(RevenueRecord.objects.filter(date=q_date,publisher=publisher).values("source__name").annotate(revenue_sum=Sum('revenue'), clicks_sum=Sum('clicks')).order_by('source__name'))

        RequestConfig(request).configure(table)
        return render(request, 'publisher_template.html', {'table': table, 'q_date': ddate, 'publisher': publisher})

demo_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Revenue Reports</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2"><a href="http://localhost:8000">Monthly Revenue Reports</a></h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

demo_app/templates/date_template.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
<head>
<title>person_list</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
<h2><a href="{% url 'demo:index' %}">Monthly Report</a></h2>
<h3>{{ q_date }}</h3>
{% render_table table %}
</body>
</html

demo_app/templates/index_template.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
<head>
<title>Dates</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
<h2><a href="{% url 'demo:index' %}">Monthly Report</a></h2>
{% render_table table %}
</body>
</html

demo_app/templates/publisher_template.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
<head>
<title>person_list</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
<h2><a href="{% url 'demo:index' %}">Monthly Report</a></h2>
<h3>{{ q_date }} - {{ publisher.name|title }}</h3>
{% render_table table %}
</body>
</html